#!/bin/sh -e

#
# Copyright (c) 2011 Simone Basso <bassosimone@gmail.com>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

# Must be at the beginning
. /usr/share/debconf/confmodule

if [ -f /var/neubot/database.sqlite3 ]; then

    INFORMED=$(sqlite3 /var/neubot/database.sqlite3 \
        'SELECT value FROM config WHERE name="privacy.informed";')
    CAN_COLLECT=$(sqlite3 /var/neubot/database.sqlite3 \
        'SELECT value FROM config WHERE name="privacy.can_collect";')

    # Backward compat
    if [ "$INFORMED" = "true" ]; then
        INFORMED=1
    fi
    if [ "$CAN_COLLECT" = "true" ]; then
        CAN_COLLECT=1
    fi

    if [ "$INFORMED" = "1" -a "$CAN_COLLECT" = "1" ]; then
        exit 0
    fi
fi

#
# The user cannot tell debconf to filter out critical
# questions.  We are sure the user will take a decision
# with respect to her IP address treatment.  Unless
# she choses the noninteractive setup.
#
db_fset neubot/privacy seen false
db_input critical neubot/privacy || true
db_go

#
# Create the database, honour user response
# and actually update settings.
#
install -d /var/neubot
sqlite3 /var/neubot/database.sqlite3 'CREATE TABLE IF NOT EXISTS config(name TEXT PRIMARY KEY, value TEXT);'

db_get neubot/privacy
if [ "$RET" = "collect only" ]; then
    INFORMED=1
    CAN_COLLECT=1
    CAN_SHARE=0
elif [ "$RET" = "collect and share" ]; then
    INFORMED=1
    CAN_COLLECT=1
    CAN_SHARE=1
else
    INFORMED=0
    CAN_COLLECT=0
    CAN_SHARE=0
fi

sqlite3 /var/neubot/database.sqlite3 "INSERT OR REPLACE INTO config(name, value) VALUES('privacy.informed', $INFORMED);"
sqlite3 /var/neubot/database.sqlite3 "INSERT OR REPLACE INTO config(name, value) VALUES('privacy.can_collect', $CAN_COLLECT);"
sqlite3 /var/neubot/database.sqlite3 "INSERT OR REPLACE INTO config(name, value) VALUES('privacy.can_share', $CAN_SHARE);"
